version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network
  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command:
      - "--changeLogFile=changelog/create-table.sql"
      - "--url=jdbc:postgresql://host.docker.internal:5432/postgres"
      - "--username=postgres"
      - "--password=postgres"
      - "update"
    networks:
      - network
networks:
  network: