version: '3'
services:
  geolocation:
    image: alyanovao/geolocation:0.0.1
    container_name: "geolocation"
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms128m-Xmx128m
    networks:
      - network
networks:
  network: